handle exception for schema create/update

diff --git a/scripts/git_hooks/pre-commit b/scripts/git_hooks/pre-commit
--- a/scripts/git_hooks/pre-commit
+++ b/scripts/git_hooks/pre-commit
@@ -1,11 +1,15 @@
-#!/bin/bash
+#!/bin/sh
 
 error() {
-    echo -e "\e[1m\e[31m$1\e[0m"
+    println "\e[1m\e[31m$1\e[0m"
 }
 
 section() {
-    echo -e "\e[33m[\e[32m\e[1m $1 \e[21m\e[33m]\e[0m"
+    println "\e[33m[\e[32m\e[1m $1 \e[21m\e[33m]\e[0m"
+}
+
+println() {
+    printf %b "$1\n"
 }
 
 lint() {
@@ -13,18 +17,18 @@ lint() {
     STAGED_FILES=$2
 
     section "start php lint"
-    echo ""
+    println ""
 
     for FILE in ${STAGED_FILES}; do
         php -l -d display_errors=0 "${PROJECT}"/"${FILE}"
 
-        if [[ $? != 0 ]]; then
+        if [ $? != 0 ]; then
             error "fix the error before commit"
             stop 1
         fi
     done
 
-    echo ""
+    println ""
     section "end php lint"
 }
 
@@ -32,12 +36,12 @@ code_sniffer() {
     STAGED_FILES=$1
 
     section "start code sniffer"
-    echo ""
+    println ""
 
     ./vendor/bin/phpcs --no-cache --encoding=utf-8 -n -p -v -s ${STAGED_FILES}
 
-    if [[ $? != 0 ]]; then
-        error "fix the following errors before commit"
+    if [ $? != 0 ]; then
+        error "fix the errors before commit"
         stop 1
     fi
 
@@ -48,7 +52,7 @@ check_php() {
     php -v > /dev/null 2>&1
     PHP_IS_INSTALLED=$?
 
-    if [[ "${PHP_IS_INSTALLED}" -ne 0 ]]; then
+    if [ "${PHP_IS_INSTALLED}" -ne 0 ]; then
         error "php is not installed"
         stop 0
     fi
@@ -63,7 +67,7 @@ PROJECT="${PWD}"
 STAGED_FILES_CMD=$(git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\.php)
 
 # determine if a file list is passed
-if [[ "$#" -eq 1 ]]; then
+if [ "$#" -eq 1 ]; then
     STAGED_FILES="$1"
 fi
 STAGED_FILES=${STAGED_FILES:-$STAGED_FILES_CMD}
@@ -72,10 +76,10 @@ section "${PROJECT} start pre commit hook"
 
 check_php
 
-if [[ "${STAGED_FILES}" != "" ]]; then
+if [ "${STAGED_FILES}" != "" ]; then
     lint "${PROJECT}" "${STAGED_FILES}"
 
-    echo ""
+    println ""
 
     code_sniffer "${STAGED_FILES}"
 fi
